# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Front.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(600, 800)
        MainWindow.setMinimumSize(QtCore.QSize(600, 800))
        MainWindow.setMaximumSize(QtCore.QSize(600, 800))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(600, 800))
        self.centralwidget.setMaximumSize(QtCore.QSize(600, 800))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(20, 20, 561, 61))
        self.titulo.setStyleSheet("font: 87 24pt \"Arial Black\";\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 127, 255));\n"
"")
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.credencial = QtWidgets.QLabel(self.centralwidget)
        self.credencial.setGeometry(QtCore.QRect(60, 120, 271, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.credencial.setFont(font)
        self.credencial.setStyleSheet("color: rgb(255, 255, 127);")
        self.credencial.setAlignment(QtCore.Qt.AlignCenter)
        self.credencial.setObjectName("credencial")
        self.buscar = QtWidgets.QPushButton(self.centralwidget)
        self.buscar.setGeometry(QtCore.QRect(390, 160, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.buscar.setFont(font)
        self.buscar.setStyleSheet("")
        self.buscar.setAutoDefault(False)
        self.buscar.setDefault(False)
        self.buscar.setFlat(False)
        self.buscar.setObjectName("buscar")
        self.serie = QtWidgets.QLineEdit(self.centralwidget)
        self.serie.setGeometry(QtCore.QRect(40, 160, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.serie.setFont(font)
        self.serie.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.serie.setMaxLength(3)
        self.serie.setAlignment(QtCore.Qt.AlignCenter)
        self.serie.setObjectName("serie")
        self.numero = QtWidgets.QLineEdit(self.centralwidget)
        self.numero.setGeometry(QtCore.QRect(180, 160, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.numero.setFont(font)
        self.numero.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.numero.setInputMethodHints(QtCore.Qt.ImhNone)
        self.numero.setMaxLength(5)
        self.numero.setAlignment(QtCore.Qt.AlignCenter)
        self.numero.setObjectName("numero")
        self.label_departamento = QtWidgets.QLabel(self.centralwidget)
        self.label_departamento.setGeometry(QtCore.QRect(20, 540, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_departamento.setFont(font)
        self.label_departamento.setStyleSheet("color: rgb(255, 255, 127);")
        self.label_departamento.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_departamento.setObjectName("label_departamento")
        self.label_circuito = QtWidgets.QLabel(self.centralwidget)
        self.label_circuito.setGeometry(QtCore.QRect(400, 540, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_circuito.setFont(font)
        self.label_circuito.setStyleSheet("color: rgb(255, 255, 127);")
        self.label_circuito.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_circuito.setObjectName("label_circuito")
        self.label_direccion = QtWidgets.QLabel(self.centralwidget)
        self.label_direccion.setEnabled(True)
        self.label_direccion.setGeometry(QtCore.QRect(20, 600, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_direccion.setFont(font)
        self.label_direccion.setStyleSheet("color: rgb(255, 255, 127);")
        self.label_direccion.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_direccion.setLineWidth(1)
        self.label_direccion.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_direccion.setObjectName("label_direccion")
        self.departamento = QtWidgets.QLineEdit(self.centralwidget)
        self.departamento.setEnabled(True)
        self.departamento.setGeometry(QtCore.QRect(150, 530, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.departamento.setFont(font)
        self.departamento.setStyleSheet("")
        self.departamento.setText("")
        self.departamento.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.departamento.setReadOnly(True)
        self.departamento.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.departamento.setObjectName("departamento")
        self.circuito = QtWidgets.QLineEdit(self.centralwidget)
        self.circuito.setEnabled(True)
        self.circuito.setGeometry(QtCore.QRect(490, 530, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.circuito.setFont(font)
        self.circuito.setMouseTracking(False)
        self.circuito.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.circuito.setAcceptDrops(False)
        self.circuito.setAccessibleName("")
        self.circuito.setStyleSheet("")
        self.circuito.setText("")
        self.circuito.setAlignment(QtCore.Qt.AlignCenter)
        self.circuito.setReadOnly(True)
        self.circuito.setObjectName("circuito")
        self.direccion = QtWidgets.QLineEdit(self.centralwidget)
        self.direccion.setEnabled(True)
        self.direccion.setGeometry(QtCore.QRect(150, 590, 431, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.direccion.setFont(font)
        self.direccion.setAcceptDrops(False)
        self.direccion.setStyleSheet("")
        self.direccion.setText("")
        self.direccion.setAlignment(QtCore.Qt.AlignCenter)
        self.direccion.setReadOnly(True)
        self.direccion.setObjectName("direccion")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 170, 21, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd.setGeometry(QtCore.QRect(80, 380, 431, 101))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lcd.setFont(font)
        self.lcd.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.lcd.setStyleSheet("color: rgb(255, 255, 127);")
        self.lcd.setFrameShape(QtWidgets.QFrame.Box)
        self.lcd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcd.setSmallDecimalPoint(False)
        self.lcd.setDigitCount(10)
        self.lcd.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcd.setObjectName("lcd")
        self.label_regresiva = QtWidgets.QLabel(self.centralwidget)
        self.label_regresiva.setGeometry(QtCore.QRect(30, 330, 541, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_regresiva.setFont(font)
        self.label_regresiva.setStyleSheet("color: rgb(255, 255, 127);")
        self.label_regresiva.setAlignment(QtCore.Qt.AlignCenter)
        self.label_regresiva.setObjectName("label_regresiva")
        self.mapa = QtWidgets.QPushButton(self.centralwidget)
        self.mapa.setEnabled(True)
        self.mapa.setGeometry(QtCore.QRect(170, 670, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mapa.setFont(font)
        self.mapa.setMouseTracking(False)
        self.mapa.setStyleSheet("")
        self.mapa.setAutoDefault(False)
        self.mapa.setDefault(False)
        self.mapa.setFlat(False)
        self.mapa.setObjectName("mapa")
        self.label_alerta = QtWidgets.QLabel(self.centralwidget)
        self.label_alerta.setGeometry(QtCore.QRect(50, 250, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_alerta.setFont(font)
        self.label_alerta.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_alerta.setText("")
        self.label_alerta.setAlignment(QtCore.Qt.AlignCenter)
        self.label_alerta.setObjectName("label_alerta")
        self.verticalFrame = QtWidgets.QFrame(self.centralwidget)
        self.verticalFrame.setGeometry(QtCore.QRect(0, 0, 600, 800))
        self.verticalFrame.setStyleSheet("background-image: url(:/newPrefix/BanderaDeUruguay.jpg);")
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.google = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.google.setGeometry(QtCore.QRect(0, 100, 601, 551))
        self.google.setStyleSheet("")
        self.google.setObjectName("google")
        self.verticalFrame.raise_()
        self.titulo.raise_()
        self.credencial.raise_()
        self.buscar.raise_()
        self.serie.raise_()
        self.numero.raise_()
        self.label.raise_()
        self.lcd.raise_()
        self.label_regresiva.raise_()
        self.mapa.raise_()
        self.circuito.raise_()
        self.departamento.raise_()
        self.direccion.raise_()
        self.label_circuito.raise_()
        self.label_direccion.raise_()
        self.label_departamento.raise_()
        self.label_alerta.raise_()
        self.google.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Elecciones Uy 2019"))
        self.titulo.setText(_translate("MainWindow", "Buscador de Circuito Electoral"))
        self.credencial.setText(_translate("MainWindow", "Ingrese su Credencial"))
        self.buscar.setText(_translate("MainWindow", "BUSCAR"))
        self.label_departamento.setText(_translate("MainWindow", "Departamento:"))
        self.label_circuito.setText(_translate("MainWindow", "Circuito:"))
        self.label_direccion.setText(_translate("MainWindow", "Direccion:"))
        self.label.setText(_translate("MainWindow", "-"))
        self.label_regresiva.setText(_translate("MainWindow", "Cuenta Regresiva para las proximas elecciones"))
        self.mapa.setText(_translate("MainWindow", "VER MAPA"))


from PyQt5 import QtWebEngineWidgets
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
